<?php

namespace DBAO\SiteBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DBAOController__JMSInjector
{
    public static function inject($container) {
        $instance = new \DBAO\SiteBundle\Controller\DBAOController();
        return $instance;
    }
}
