dbao_utilisateur:
    resource: "@DBAOUtilisateurBundle/Resources/config/routing.yml"
    prefix:   /

dbao_admin:
    resource: "@DBAOAdminBundle/Resources/config/routing.yml"
    prefix:   /dbao/admin

dbao_site:
    resource: "@DBAOSiteBundle/Resources/config/routing.yml"
    prefix:   /dbao
