parameters:
#    dbao_site.example.class: DBAO\SiteBundle\Example

services:
#    dbao_site.example:
#        class: %dbao_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
