<?php

namespace DBAO\AdminBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AgenceController__JMSInjector
{
    public static function inject($container) {
        $instance = new \DBAO\AdminBundle\Controller\AgenceController();
        return $instance;
    }
}
